<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="\\iscsi\profstud\borodachevvs\Desktop\OOP_Fundamentals_Library\OOP_Fundamentals_Library.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="OOP_Fundamentals_Library">
      <HintPath>\\iscsi\profstud\borodachevvs\Desktop\OOP_Fundamentals_Library\bin\Debug\net9.0\OOP_Fundamentals_Library.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
